import { Router } from 'express';
import { authenticate } from '../middleware/auth.js';
import { fulkyController } from '../controllers/fulkyController.js';
const router = Router();
router.use(authenticate);
router.post('/sessions', fulkyController.open.bind(fulkyController));
router.get('/context', fulkyController.context.bind(fulkyController));
router.post('/messages', fulkyController.message.bind(fulkyController));
router.post('/sessions/:conversationId/close', fulkyController.close.bind(fulkyController));
export default router;
