"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { AUTH_TOKEN_KEY } from "@/lib/auth";
import styles from "./FulkyAssistant.module.css";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5000/api";
type Product = { _id: string; name: string; description: string; price: number; currency?: string; packSize?: string; stock: number; images?: string[]; tone?: string };
type Message = { role: 'customer' | 'agent'; content: string; products?: Product[] };
export function FulkyAssistant() {
 const [open,setOpen]=useState(false),[conversation,setConversation]=useState(''),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[state,setState]=useState('READY'),[error,setError]=useState('');
 const recognition=useRef<any>(null); const token=()=>localStorage.getItem(AUTH_TOKEN_KEY)||''; const headers=()=>({'Content-Type':'application/json',Authorization:`Bearer ${token()}`});
 useEffect(()=>()=>{ if(conversation) fetch(`${api}/fulky/sessions/${conversation}/close`,{method:'POST',headers:headers()}); },[conversation]);
 async function show(){setOpen(true);setError(''); if(conversation)return; try{const r=await fetch(`${api}/fulky/sessions`,{method:'POST',headers:headers()});const d=await r.json();if(!r.ok)throw Error(d.error);setConversation(d.conversationId);setMessages([{role:'agent',content:d.greeting}]);}catch(e){setError(e instanceof Error?e.message:'Fulky could not connect.');}}
 async function send(value:string){if(!value.trim()||!conversation)return;setMessages(m=>[...m,{role:'customer',content:value}]);setText('');setState('THINKING');try{const r=await fetch(`${api}/fulky/messages`,{method:'POST',headers:headers(),body:JSON.stringify({conversationId:conversation,text:value})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessages(m=>[...m,{role:'agent',content:d.reply,products:d.products}]);setState('READY');}catch(e){setError(e instanceof Error?e.message:'Fulky could not reply.');setState('ERROR');}}
 function voice(){const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setError('Fulky needs microphone access to chat by voice. Try text instead.');return;}const r=new Speech();recognition.current=r;r.continuous=false;r.interimResults=true;r.onstart=()=>setState('LISTENING');r.onresult=(e:any)=>{const spoken=Array.from(e.results).map((x:any)=>x[0].transcript).join('');setText(spoken);if(e.results[e.results.length-1].isFinal)send(spoken);};r.onerror=()=>{setState('ERROR');setError('Fulky needs microphone access to chat by voice. Try text instead.');};r.onend=()=>setState(s=>s==='THINKING'?s:'READY');r.start();}
 function add(product:Product){const key='fizzy-basket-v1';const items=JSON.parse(localStorage.getItem(key)||'[]');const found=items.find((i:any)=>i.id===product._id);localStorage.setItem(key,JSON.stringify(found?items.map((i:any)=>i.id===product._id?{...i,quantity:i.quantity+1}:i):[...items,{id:product._id,quantity:1}]));window.dispatchEvent(new Event('fizzi-basket-change'));setMessages(m=>[...m,{role:'agent',content:`Added ${product.name} to your basket.`}]);}
 return <><button className={styles.trigger} onClick={show}><span>◖◗</span>Ask Fulky</button>{open&&<><button className={styles.backdrop} aria-label="Close Fulky" onClick={()=>setOpen(false)}/><aside className={styles.drawer}><header><div className={styles.avatar}><i/><i/></div><div><b>FULKY</b><p>Your personal Fizzi drink guide</p></div><button onClick={()=>setOpen(false)}>×</button></header><div className={styles.status}><span className={state==='ERROR'?styles.bad:''}/>Fulky is {state.toLowerCase()}</div><div className={styles.timeline}>{messages.map((m,i)=><div key={i} className={m.role=== 'customer'?styles.customer:styles.agent}><p>{m.content}</p>{m.products?.map(product=><article className={styles.card} key={product._id}><div className={styles.productArt} style={{background:product.tone||'#41C9E2'}}>{product.images?.[0]&&<img src={product.images[0]} alt=""/>}<b>fizzi</b></div><div><strong>{product.name}</strong><small>{product.description}</small><em>{new Intl.NumberFormat('en-IN',{style:'currency',currency:product.currency||'INR'}).format(product.price)} · {product.packSize||'case'}</em><button onClick={()=>add(product)}>Add to basket</button></div></article>)}</div>)}</div>{error&&<p className={styles.error}>{error}</p>}<div className={styles.voice}><div className={state==='LISTENING'?styles.waveActive:styles.wave}>▁▃▆▃▁</div><button onClick={voice}>🎙<span>{state==='LISTENING'?'Listening…':'Talk to Fulky'}</span></button></div><form onSubmit={(e:FormEvent)=>{e.preventDefault();send(text)}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask Fulky anything…"/><button>Send</button></form></aside></>}</>;
}
